#:schema node_modules/wrangler/config-schema.json
name = "talk-to-javascript"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[ai]
binding = "AI"

[assets]
directory = "./public"

[[durable_objects.bindings]]
name = "GIFT_LIST"
class_name = "GiftListStore"

[[migrations]]
tag = "v1"
new_classes = [ "GiftListStore" ]
